---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-app
  labels:
    app: batch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-app
  template:
    metadata:
      labels:
        app: batch-app
    spec:
      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: batch-app
          image: %DOCKER_IMAGE%
          resources:
            requests:
              memory: "512Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          env:
            - name: AWSRegion
              value: us-east-1              
            - name: s3InputBucket
              value: %S3INPUTBUCKET% 
            - name: s3OutputBucket
              value: %S3OUTPUTBUCKET% 
            - name: SQSBatchQueue
              value: %SQSQUEUE%                