AWSTemplateFormatVersion: 2010-09-09
Description: >-
  IAM role for serviceaccount "kube-system/aws-node" [created and managed by
  eksctl]
Resources:
  Role1:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'oidc.eks.ap-southeast-2.amazonaws.com/id/349F4D6DDA3CD1C4F34271DE77BDA9CE:aud': sts.amazonaws.com
                'oidc.eks.ap-southeast-2.amazonaws.com/id/349F4D6DDA3CD1C4F34271DE77BDA9CE:sub': 'system:serviceaccount:kube-system:aws-node'
            Effect: Allow
            Principal:
              Federated: >-
                arn:aws:iam::652975927388:oidc-provider/oidc.eks.ap-southeast-2.amazonaws.com/id/349F4D6DDA3CD1C4F34271DE77BDA9CE
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
Outputs:
  Role1:
    Value: !GetAtt Role1.Arn
