---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              memory: "512Mi"
              cpu: "1024m"
            limits:
              memory: "512Mi"
              cpu: "1024m"
          ports:
            - containerPort: 80