---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-split-spread 
  labels: 
    app: nginx-split-spread 
spec: 
  replicas: 12
  selector: 
    matchLabels: 
      app: nginx-split-spread 
  template: 
    metadata: 
      labels: 
        app: nginx-split-spread 
    spec:
      tolerations: 
      - key: "spotInstance" 
        operator: "Equal" 
        value: "true" 
        effect: "PreferNoSchedule" 
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway 
        labelSelector:
          matchLabels:
            app: nginx-split-spread
      containers: 
        - name: nginx-split-spread 
          image: nginx:1.14.2
          resources: 
            requests: 
              memory: "512Mi" 
              cpu: "1024m" 
            limits: 
              memory: "512Mi" 
              cpu: "1024m" 
          ports: 
            - containerPort: 80

