---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-split 
  labels: 
    app: nginx-split 
spec: 
  replicas: 12
  selector: 
    matchLabels: 
      app: nginx-split 
  template: 
    metadata: 
      labels: 
        app: nginx-split 
    spec:
      tolerations: 
      - key: "spotInstance" 
        operator: "Equal" 
        value: "true" 
        effect: "PreferNoSchedule" 
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 75
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - Ec2Spot                 
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 25
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - OnDemand
      containers: 
        - name: nginx-split 
          image: nginx:1.14.2
          resources: 
            requests: 
              memory: "512Mi" 
              cpu: "1024m" 
            limits: 
              memory: "512Mi" 
              cpu: "1024m" 
          ports: 
            - containerPort: 80

