apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: eks-spot-demo
    region: us-east-1
nodeGroups:
    - name: SPOT
      minSize: 0
      maxSize: 5
      desiredCapacity: 0
      instancesDistribution:
        instanceTypes: ["m5.large", "m4.large", "c5.large", "c4.large", "r5.large", "r4.large"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: capacity-optimized
      labels:
        lifecycle: SPOT
        env: prod
        aws.amazon.com/spot: "true"
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: SPOT
        k8s.io/cluster-autoscaler/node-template/label/env: prod
        k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot: "true"
      iam:
        withAddonPolicies:
          autoScaler: true
          cloudWatch: true
          albIngress: true
    - name: OnDemand
      minSize: 0
      maxSize: 5
      desiredCapacity: 0
      instancesDistribution:
        instanceTypes: ["m5.large", "m4.large", "c5.large", "c4.large", "r5.large", "r4.large"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 100
        spotAllocationStrategy: capacity-optimized
      labels:
        lifecycle: OD
        env: prod
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: OD
        k8s.io/cluster-autoscaler/node-template/label/env: prod
      iam:
        withAddonPolicies:
          autoScaler: true
          cloudWatch: true
          albIngress: true
